<?php
/**
 * Autoloader definition for eZ Publish Extension files.
 *
 * @copyright Copyright (C) 1999-2010 eZ Systems AS. All rights reserved.
 * @license http://ez.no/licenses/gnu_gpl GNU GPL v2
 * @version 4.3.0
 * @package kernel
 *
 */

return array(
      'BaseHandler'                        => 'extension/collectexport/modules/collectexport/basehandler.php',
      'EnchantSpell'                       => 'extension/ezoe/modules/ezoe/classes/EnchantSpell.php',
      'GoogleSpell'                        => 'extension/ezoe/modules/ezoe/classes/GoogleSpell.php',
      'JSMin'                              => 'extension/ezjscore/lib/jsmin.php',
      'JSMinException'                     => 'extension/ezjscore/lib/jsmin.php',
      'Moxiecode_JSON'                     => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'Moxiecode_JSONReader'               => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'PSpell'                             => 'extension/ezoe/modules/ezoe/classes/PSpell.php',
      'PSpellShell'                        => 'extension/ezoe/modules/ezoe/classes/PSpellShell.php',
      'Parser'                             => 'extension/collectexport/modules/collectexport/parser.php',
      'SpellChecker'                       => 'extension/ezoe/modules/ezoe/classes/SpellChecker.php',
      'collectexportInfo'                  => 'extension/collectexport/ezinfo.php',
      'eZCommentsInfo'                     => 'extension/ezcomments/ezinfo.php',
      'eZContentClassEditDeferredHandler'  => 'extension/ezscriptmonitor/classes/ezcontentclasseditdeferredhandler.php',
      'eZDBFileHandlerOracleBackend'       => 'extension/ezoracle/clusterfilehandlers/dbbackends/oracle.php',
      'eZDFSFileHandlerOracleBackend'      => 'extension/ezoracle/clusterfilehandlers/dfsbackends/oracle.php',
      'eZEmailHandler'                     => 'extension/collectexport/modules/collectexport/ezemailhandler.php',
      'eZFindElevateConfiguration'         => 'extension/ezfind/classes/ezfindelevateconfiguration.php',
      'eZFindInfo'                         => 'extension/ezfind/ezinfo.php',
      'eZFindResultNode'                   => 'extension/ezfind/classes/ezfindresultnode.php',
      'eZFindResultObject'                 => 'extension/ezfind/classes/ezfindresultobject.php',
      'eZFindServerCallFunctions'          => 'extension/ezfind/classes/ezfindservercallfunctions.php',
      'eZFloatHandler'                     => 'extension/collectexport/modules/collectexport/ezfloathandler.php',
      'eZIdentifierHandler'                => 'extension/collectexport/modules/collectexport/ezidentifierhandler.php',
      'eZIntegerHandler'                   => 'extension/collectexport/modules/collectexport/ezintegerhandler.php',
      'eZMultiuploadHandler'               => 'extension/ezmultiupload/classes/ezmultiuploadhandler.php',
      'eZMultiuploadHandlerInterface'      => 'extension/ezmultiupload/classes/ezmultiuploadhandlerinterface.php',
      'eZOEInputParser'                    => 'extension/ezoe/ezxmltext/handlers/input/ezoeinputparser.php',
      'eZOETemplateUtils'                  => 'extension/ezoe/autoloads/ezoetemplateutils.php',
      'eZOEXMLInput'                       => 'extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php',
      'eZOOConverter'                      => 'extension/ezodf/classes/ezooconverter.php',
      'eZOOGenerator'                      => 'extension/ezodf/classes/ezoogenerator.php',
      'eZOOImport'                         => 'extension/ezodf/classes/ezooimport.php',
      'eZOpenofficeUploadHandler'          => 'extension/ezodf/uploadhandlers/ezopenofficeuploadhandler.php',
      'eZOracleDB'                         => 'extension/ezoracle/ezdb/dbms-drivers/ezoracledb.php',
      'eZOracleSchema'                     => 'extension/ezoracle/ezdb/dbms-schema/ezoracleschema.php',
      'eZPaEx'                             => 'extension/ezmbpaex/classes/ezpaex.php',
      'eZPaExUser'                         => 'extension/ezmbpaex/login_handler/ezpaexuser.php',
      'eZRESTODFHandler'                   => 'extension/ezodf/classes/ezrestodfhandler.php',
      'eZScheduledScript'                  => 'extension/ezscriptmonitor/classes/ezscheduledscript.php',
      'eZScriptMonitorInfo'                => 'extension/ezscriptmonitor/ezinfo.php',
      'eZSelectionHandler'                 => 'extension/collectexport/modules/collectexport/ezselectionhandler.php',
      'eZSolr'                             => 'extension/ezfind/search/plugins/ezsolr/ezsolr.php',
      'eZSolrBase'                         => 'extension/ezfind/classes/ezsolrbase.php',
      'eZSolrDoc'                          => 'extension/ezfind/classes/ezsolrdoc.php',
      'eZStringHandler'                    => 'extension/collectexport/modules/collectexport/ezstringhandler.php',
      'eZSurvey'                           => 'extension/ezsurvey/modules/survey/classes/ezsurvey.php',
      'eZSurveyEmailEntry'                 => 'extension/ezsurvey/modules/survey/classes/ezsurveyemailentry.php',
      'eZSurveyEntry'                      => 'extension/ezsurvey/modules/survey/classes/ezsurveyentry.php',
      'eZSurveyFormattedParagraph'         => 'extension/ezsurvey/modules/survey/classes/ezsurveyformattedparagraph.php',
      'eZSurveyMetaData'                   => 'extension/ezsurvey/modules/survey/classes/ezsurveymetadata.php',
      'eZSurveyMultipleChoice'             => 'extension/ezsurvey/modules/survey/classes/ezsurveymultiplechoice.php',
      'eZSurveyNumberEntry'                => 'extension/ezsurvey/modules/survey/classes/ezsurveynumberentry.php',
      'eZSurveyOperators'                  => 'extension/ezsurvey/modules/survey/classes/ezsurveyoperators.php',
      'eZSurveyParagraph'                  => 'extension/ezsurvey/modules/survey/classes/ezsurveyparagraph.php',
      'eZSurveyQuestion'                   => 'extension/ezsurvey/modules/survey/classes/ezsurveyquestion.php',
      'eZSurveyQuestionMetaData'           => 'extension/ezsurvey/modules/survey/classes/ezsurveyquestionmetadata.php',
      'eZSurveyQuestionResult'             => 'extension/ezsurvey/modules/survey/classes/ezsurveyquestionresult.php',
      'eZSurveyReceiver'                   => 'extension/ezsurvey/modules/survey/classes/ezsurveyreceiver.php',
      'eZSurveyRelatedConfig'              => 'extension/ezsurvey/modules/survey/classes/ezsurveyrelatedconfig.php',
      'eZSurveyRelatedObject'              => 'extension/ezsurvey/modules/survey/classes/ezsurveyrelatedobject.php',
      'eZSurveyResult'                     => 'extension/ezsurvey/modules/survey/classes/ezsurveyresult.php',
      'eZSurveySectionHeader'              => 'extension/ezsurvey/modules/survey/classes/ezsurveysectionheader.php',
      'eZSurveyTextEntry'                  => 'extension/ezsurvey/modules/survey/classes/ezsurveytextentry.php',
      'eZSurveyType'                       => 'extension/ezsurvey/datatypes/ezsurvey/ezsurveytype.php',
      'eZSurveyWizard'                     => 'extension/ezsurvey/modules/survey/classes/ezsurveywizard.php',
      'eZTextHandler'                      => 'extension/collectexport/modules/collectexport/eztexthandler.php',
      'eZURLHandler'                       => 'extension/collectexport/modules/collectexport/ezurlhandler.php',
      'eZXMLTextHandler'                   => 'extension/collectexport/modules/collectexport/ezxmltexthandler.php',
      'ezcomAddCommentTool'                => 'extension/ezcomments/classes/ezcomaddcommenttool.php',
      'ezcomComment'                       => 'extension/ezcomments/classes/ezcomcomment.php',
      'ezcomCommentCommonManager'          => 'extension/ezcomments/classes/ezcomcommentcommonmanager.php',
      'ezcomCommentManager'                => 'extension/ezcomments/classes/ezcomcommentmanager.php',
      'ezcomCommentsType'                  => 'extension/ezcomments/datatypes/ezcomcomments/ezcomcommentstype.php',
      'ezcomCookieManager'                 => 'extension/ezcomments/classes/ezcomcookiemanager.php',
      'ezcomEditCommentTool'               => 'extension/ezcomments/classes/ezcomeditcommenttool.php',
      'ezcomFormTool'                      => 'extension/ezcomments/classes/ezcomformtool.php',
      'ezcomFunctionCollection'            => 'extension/ezcomments/classes/ezcomfunctioncollection.php',
      'ezcomNotification'                  => 'extension/ezcomments/classes/ezcomnotification.php',
      'ezcomNotificationEmailManager'      => 'extension/ezcomments/classes/ezcomnotificationemailmanager.php',
      'ezcomNotificationManager'           => 'extension/ezcomments/classes/ezcomnotifcationmanager.php',
      'ezcomPermission'                    => 'extension/ezcomments/classes/ezcompermission.php',
      'ezcomPostHelper'                    => 'extension/ezcomments/classes/ezcomposthelper.php',
      'ezcomServerFunctions'               => 'extension/ezcomments/classes/ezcomserverfunctions.php',
      'ezcomSubscriber'                    => 'extension/ezcomments/classes/ezcomsubscriber.php',
      'ezcomSubscription'                  => 'extension/ezcomments/classes/ezcomsubscription.php',
      'ezcomSubscriptionManager'           => 'extension/ezcomments/classes/ezcomsubscriptionmanager.php',
      'ezcomUtility'                       => 'extension/ezcomments/classes/ezcomutility.php',
      'ezenhancedobjectrelationHandler'    => 'extension/collectexport/modules/collectexport/ezenhancedobjectrelationhandler.php',
      'ezfModuleFunctionCollection'        => 'extension/ezfind/classes/ezfmodulefunctioncollection.php',
      'ezfSearchResultInfo'                => 'extension/ezfind/classes/ezfsearchresultinfo.php',
      'ezfSolrDocumentFieldBase'           => 'extension/ezfind/classes/ezfsolrdocumentfieldbase.php',
      'ezfSolrDocumentFieldDummyExample'   => 'extension/ezfind/classes/ezfsolrdocumentfielddummyexample.php',
      'ezfSolrDocumentFieldName'           => 'extension/ezfind/classes/ezfsolrdocumentfieldname.php',
      'ezfSolrDocumentFieldObjectRelation' => 'extension/ezfind/classes/ezfsolrdocumentfieldobjectrelation.php',
      'ezfSolrDocumentFieldXML'            => 'extension/ezfind/classes/ezfsolrdocumentfieldxml.php',
      'ezfUpdateSearchIndexSolr'           => 'extension/ezfind/bin/php/updatesearchindexsolr.php',
      'ezfeZPSolrQueryBuilder'             => 'extension/ezfind/classes/ezfezpsolrquerybuilder.php',
      'ezjscAccessTemplateFunctions'       => 'extension/ezjscore/autoloads/ezjscaccesstemplatefunctions.php',
      'ezjscAjaxContent'                   => 'extension/ezjscore/classes/ezjscajaxcontent.php',
      'ezjscEncodingTemplateFunctions'     => 'extension/ezjscore/autoloads/ezjscencodingtemplatefunctions.php',
      'ezjscPacker'                        => 'extension/ezjscore/classes/ezjscpacker.php',
      'ezjscPackerTemplateFunctions'       => 'extension/ezjscore/autoloads/ezjscpackertemplatefunctions.php',
      'ezjscServerFunctions'               => 'extension/ezjscore/classes/ezjscserverfunctions.php',
      'ezjscServerFunctionsJs'             => 'extension/ezjscore/classes/ezjscserverfunctionsjs.php',
      'ezjscServerRouter'                  => 'extension/ezjscore/classes/ezjscserverrouter.php',
      'ezjscoreInfo'                       => 'extension/ezjscore/ezinfo.php',
      'ezmbpaexInfo'                       => 'extension/ezmbpaex/ezinfo.php',
      'ezmultiuploadInfo'                  => 'extension/ezmultiupload/ezinfo.php',
      'ezodfInfo'                          => 'extension/ezodf/ezinfo.php',
      'ezoeInfo'                           => 'extension/ezoe/ezinfo.php',
      'ezoeServerFunctions'                => 'extension/ezoe/classes/ezoeserverfunctions.php',
      'ezoracleInfo'                       => 'extension/ezoracle/ezinfo.php',
      'ezpaextype'                         => 'extension/ezmbpaex/datatypes/ezpaex/ezpaextype.php',
      'ezsurveyInfo'                       => 'extension/ezsurvey/ezinfo.php',
      'navFilter'                          => 'extension/neteext/classes/navfilter.php',
      'navigationFunctionCollection'       => 'extension/neteext/modules/navigation/navigationfunctioncollection.php',
    );

?>