<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "contact_us",
                     "development" => false,
                     "summary" => "Export of content class Contact Us",
                     "description" => "This package contains an exported definition of the content class Contact Us which can be imported to another eZ Publish site",
                     "vendor" => false,
                     "vendor-dir" => "local",
                     "priority" => false,
                     "type" => "contentclass",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "4.3.0",
                                           "named-version" => "4.3" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "akhilesh.singh@netesoft.com",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1304076252",
                                           "host" => "192.168.0.11",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1304076252",
                                                  "person" => "Administrator User",
                                                  "email" => "akhilesh.singh@netesoft.com",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array(),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array( array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "contact_form" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "type" => "ezcontentclass",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "class-contact_form",
                                                "sub-directory" => "ezcontentclass" ) ),
                     "uninstall" => array( array( "type" => "ezcontentclass",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "class-contact_form",
                                                  "sub-directory" => "ezcontentclass" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/local";
?>
